### ISSUE TITLE
ScanNet200 data structure

### ISSUE THREAD

**Issue by YilmazKadir** [OpenMask3D/openmask3d#12]
I try to evaluate OpenMask3D on the ScanNet200 dataset. I did not quite understand how I can make sure the data is in the format provided here:

![image](https://github.com/OpenMask3D/openmask3d/assets/59517677/2d200d37-26f2-4651-9eab-8c441e389140)

The raw dataset has the following format:
![image](https://github.com/OpenMask3D/openmask3d/assets/59517677/fdbe2a89-a436-4c73-aac8-fb86f36fff5a)

When I run the preprocessing script I only get the preprocessed numpy files:
![image](https://github.com/OpenMask3D/openmask3d/assets/59517677/23b572df-6b09-48dc-b699-9f456799e83a)

**Comment by aycatakmaz** [comment]
Hi Kadir,

The ScanNet preprocessing script we provided in the repository is for being able to run the mask-proposal network, it is the same preprocessing script used in Mask3D. So that script only results in the preprocessed numpy files you mentioned.

The RGB-D images for the ScanNet dataset can be obtained using the ScanNet toolbox to extract RGB-D frames from the .sens files for each scene. You can find further details [here](http://www.scan-net.org/ScanNet/) and [here](http://www.scan-net.org/ScanNet/SensReader/python/).

Alternatively, [OpenScene](https://github.com/pengsongyou/openscene) release includes an easily downloadable version for RGB-D images and camera poses for the ScanNet dataset. Please note that if you would like to run OpenMask3D on those frames, you might need to change the frequency parameter in our config, based on the frame rate used in OpenScene. I think those frames are already sampled and saved based on that chosen rate (10 if I remember correctly). In that case, the frequency parameter in our config should be set to 1. Nevertheless, I would recommend you double-check the frame rate in OpenScene to make sure it corresponds to our setting.

I hope this answers your question!

**Comment by aycatakmaz** [comment]
I am closing the issue, feel free to re-open it if any other questions related to this topic emerge!

**Comment by YilmazKadir** [comment]
Thank you for the answer. OpenScene uses every 20 frames so I had to process it as in the SensReader in ScanNet toolbox. One thing important to mention is that RGB images need to be resized to 640x480. After this, I got the same results as the ScanNet table in the paper.
