### ISSUE TITLE
How to understand the model output and get segmented point cloud?

### ISSUE THREAD

**Issue by pranav-satheesan** [OpenMask3D/openmask3d#13]
I ran the model on sample scene using the model checkpoints and now I have a 222x768 dimensional output matrix (scene_example_openmask3d_features.npy). How to prompt and get the segmented point cloud? Say, if I want to get 'The TV on the wall'. What should I do?

**Comment by aycatakmaz** [comment]
Hi!

We have pushed a commit that adds a simple visualization script [viz_sim_score_export.py](https://github.com/OpenMask3D/openmask3d/blob/main/openmask3d/visualization/viz_sim_score_export.py). In order to visualize similarity scores between the OpenMask3D features and the query embedding as a heatmap, one just needs to set the following variables:

path_scene_pcd: Path to the scene point cloud/mesh (.ply)
path_pred_masks: Path to the predicted instance masks (.pt)
path_openmask3d_features: Path to the per-mask OpenMask3D features (*.npy)
query_text: Intended query text as a string, e.g. "watch a movie"
The script will automatically visualize the similarity scores as a heatmap, and show the results in an Open3D visualization window. Alternatively, you can also export a .ply file with the point cloud colored with the similarity heatmap colors per point.

In the script, you can see how we retrieve the object masks given a prompt, based on the feature similarity between the mask features and query features.

Hope this helps!

**Comment by pranav-satheesan** [comment]
Thank you very much for your help. I was able to get the .ply file with the colored point cloud. The results were quite impressive. 
I wanted to test this with a dataset of my own. Is there some android/IOS mobile app which exports point cloud along with RGBD images? There are some which gives only .ply files and not depth images. I am very new to this field, your help will be invaluable.

**Comment by aycatakmaz** [comment]
Glad to hear that the visualization worked out!

Regarding capturing RGB-D and point cloud from a mobile app, I have previously used an app called [3D Scanner App](https://apps.apple.com/de/app/3d-scanner-app/id1419913995), but as far as I know this app only works with a device that has a Lidar sensor. If you have access to a device with similar capabilities, I can recommend this app!

**Comment by aycatakmaz** [comment]
I am closing the issue, feel free to re-open it if any other questions related to this topic emerge!

**Comment by pranav-satheesan** [comment]
Hello Ayca.
I used the 3D Scanner App you mentioned. I tried to export the scene from that app. I tried the export 'all data' option when exporting the scene (see attached image below), but could only get color images and not 'depth' images. 

![Image](https://github.com/OpenMask3D/openmask3d/assets/124446551/d5399d8e-18f6-4747-a249-dbcd2f38f4c9)

Can you please tell me how to get depth maps along with rgb images.?? Is there some other export filetype which would yield depth images also???
Thank you

**Comment by aycatakmaz** [comment]
Hi,

I checked and there are a couple of different ways to get depth maps.

- If you use the **LIDAR Advanced** mode and export the data using the **All Data** option, this mode automatically gives you a very high quality reconstructed mesh (see `export_refined.obj`), and RGB frames. Furthermore, the camera poses are available in the `frame_XXXXX.json` files. By using the camera poses, one can render depth frames from the reconstructed mesh using a library such as Open3D.

- If you use the **Point Cloud** mode and export the data using the **All Data** option, this mode extracts the depth images, and camera poses at each frame. One issue with this mode is that the RGB image frequency is not the same as the depth image frequency. In that case, you can simply move your camera slowly, and only use the frames for which an RGB image and a depth image is available. I haven't explored what other options are available for this mode, but in my case it seemed like I was able to get 1 RGB frame for every 7 depth frames - not sure if this can be adjusted somehow from the app.

Hope this helps!

Best,
Ayca

**Comment by aycatakmaz** [comment]
Here is a simplified script that uses the data from the Lidar Advanced mode and renders depth images from the reconstructed refined mesh:

```python
import os
import json
import copy
import open3d as o3d
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from tqdm import tqdm

# IMPORTANT! Set the following variables based on your setup!
img_width, img_height = (IMG_WIDTH, IMG_HEIGHT)
data_prefix = 'PATH/TO/LIDAR_ADVANCED/ALL_DATA'
save_data_prefix = 'PATH/TO/DEPTH_DATA_SAVE_DIR'

mesh = o3d.io.read_triangle_mesh(os.path.join(data_prefix, 'export_refined.obj'))
mesh.compute_vertex_normals()  # only for easier debugging
near_plane = 0.1 # in meters
far_plane = 20. #in meters

# Camera poses in world coordinate system
poses = sorted([f for f in os.listdir(os.path.join(data_prefix, 'poses')) if f.endswith('.json') and f.startswith('frame')])

def move_forward(file):
    file_name = file[6:11]

        # Load camera extrinsics and intrinsics
    with open(os.path.join(data_prefix, 'poses', file[:-4]+'json')) as f:
        json_file = json.load(f)
    intrinsics = np.array(json_file['intrinsics']).reshape([3, 3])
    extrinsics = np.array(json_file['cameraPoseARFrame']).reshape([4, 4])

    # Rotation matrix around x-axis, 180 degrees (pi radians)
    a_x = np.pi
    rot_x = np.eye(3)
    rot_x[1, 1] = np.cos(a_x)
    rot_x[1, 2] = -np.sin(a_x)
    rot_x[2, 1] = np.sin(a_x)
    rot_x[2, 2] = np.cos(a_x)

    # Adapt camera pose for correct depth rendering
    rot = extrinsics[0:3, 0:3] @ rot_x
    t = extrinsics[0:3, 3]
    pose = np.eye(4)
    pose[0:3, 0:3] = rot
    pose[0:3, 3] =  t

    # Convert from world to camera coordinate system
    pose_inv = np.eye(4)
    pose_inv[0:3, 0:3] = rot.T
    pose_inv[0:3, 3] = -rot.T @ t

    cam = o3d.camera.PinholeCameraParameters()
    cam.extrinsic = np.array(pose_inv)
    cam.intrinsic = o3d.camera.PinholeCameraIntrinsic(img_width, img_height, intrinsics[0,0], intrinsics[1,1], intrinsics[0,2], intrinsics[1,2])

    transformed_mesh = copy.deepcopy(mesh)
    transformed_mesh.compute_vertex_normals() 

    # set renderers
    material = o3d.visualization.rendering.MaterialRecord()        
    renderer = o3d.visualization.rendering.OffscreenRenderer(img_width, img_height)

    # don't mess up with pixel values!
    renderer.scene.view.set_post_processing(False)

    # set camera projection
    renderer.setup_camera(cam.intrinsic, cam.extrinsic)
    renderer.scene.camera.set_projection(intrinsics, near_plane, far_plane, img_width, img_height)

    # add scene
    renderer.scene.add_geometry("mesh", transformed_mesh, material)

    # render depth image
    depth_image = renderer.render_to_depth_image(z_in_view_space=True)
    depth_image_array = np.asarray(depth_image)

    # normalize depth image - only for visualization
    normalized_depth_image = depth_image_array.copy()
    normalized_depth_image[normalized_depth_image>far_plane] = 0
    normalized_depth_image = (normalized_depth_image - normalized_depth_image.min()) / (normalized_depth_image.max() - normalized_depth_image.min())
    
    # save depth array and depth image
    np.save(f"{save_data_prefix}/depth_{file_name}.npy", depth_image_array)
    plt.imsave(f"{save_data_prefix}/depth_{file_name}.png", normalized_depth_image)

for file in tqdm(poses):
    move_forward(file)
```

**Comment by pranav-satheesan** [comment]
Hi Ayca,
I exported my data using both the methods. But the results are not good. I followed these instructions https://francisengelmann.github.io/mask3d/
I was wondering if there is any additional preprocessing to be done? (like changing the changing depth_scale etc. or any other value).
Also the script provided above renders depth maps having multiple channels, which gave error. I took mean of values across channels for each pixel and made it into a single channel depth map. Is it correct?

**Comment by aycatakmaz** [comment]
Hi,

Yes, you should change the`intrinsic_resolution` parameter and the `depth_scale` in the config. Intrinsic resolution should be set to the image resolution according to the camera intrinsic matrix you are giving as input. Depth scale should also be set accordingly. If your depth values are in metric scale, `depth_scale` should be set to 1.

**Comment by pranav-satheesan** [comment]
Can you tell me the formula to calculate intrinsic resolution?
For scannet scene provided by you, intrinsic is:
[[1169,0,646,0],[0,1167,490,0],[0,0,1,0],[0,0,0,1]] and 
SCENE_INTRINSIC_RESOLUTION="[968,1296]".

**Comment by pranav-satheesan-mphasis** [comment]
Hello Ayca,
I tried running your model on data from 3D Scanner App and it was not performing good. So I did the following transformtions to the data based on the configurations mentioned in the App's developer website and what the model required

1) Since the scan captured was a y axis up, I converted it to z-axis up by matrix transformations
2) Since the RGB images were in 1440x1920, I made the depth image from the above code you gave me of the same size (1920x1440). Also normalization was giving me bad results, so I capped the points at infinity to the far_plane (which in my case was 4 metres) 
When I did this and looked at the results, it were still not good.
3) So, I resized the color image and depth map both into 640x480 (because scannet data was like this).
But still no result. 
the PointCloud mode with All Data option was further more worse (maybe because of less RGB images ~80-100 images)

Also i reduced the frequency parameter to 1 instead of 10 as I have less RGBD data (of the order of 100-200 in either mode)

Now I wanted to understand what all more data transformations/ preprocessing steps are there which I am missing out?


For reference, the image attached for the prompt: "The chair in the scene" on my own data
![image](https://github.com/OpenMask3D/openmask3d/assets/142482109/b41bd42b-9fb7-48a7-a8e2-93e2c281481a)

As you can see, it is giving floor as the segment with highest confidence instead of the chair itself.

Now I wanted to understand what all more data transformations/ preprocessing steps are there which I am missing out?
A little help would be deeply appreciated.  
Regards,
Pranav
