### ISSUE TITLE
wrong crops on own dataset

### ISSUE THREAD

**Issue by parodiniccolo** [OpenMask3D/openmask3d#16]
Hi all :)

I'm trying to run openmask3D with data recorded with the PolyCam iOS app. From PolyCam I can export a pointcloud.ply file of the scene (Z up), images, depth and .json file per each frame that hold the camera intrinsics and extrinsics, as well as the image width, height and a blur_score. See details [here](https://github.com/PolyCam/polyform/tree/main)

.json example:

>  {
>   "t_00" : 0.17319575,
>   "blur_score" : 32.372955,
>   "cx" : 507.0329,
>   "t_22" : 0.8309242,
>   "t_02" : 0.45727086,
>   "t_21" : -0.48847204,
>   "t_12" : 0.3169675,
>   "t_23" : -24.16848,
>   "center_depth" : 4.009069,
>   "timestamp" : 65505281644,
>   "height" : 768,
>   "t_10" : -0.9481788,
>   "t_03" : -4.817948,
>   "t_20" : 0.2663835,
>   "manual_keyframe" : false,
>   "t_13" : 0.65569174,
>   "width" : 1024,
>   "fy" : 849.0737,
>   "angular_velocity" : 3.4028235e+38,
>   "cy" : 383.2808,
>   "t_01" : 0.8722997,
>   "fx" : 849.0737,
>   "t_11" : 0.022103118
> }

> The t_ij element of the transform matrix is in row-major order, so i is the row and j is the column. We omit the last row because it is simply [0, 0, 0, 1].

```math
\begin{bmatrix}
t_{00} & t_{01} & t_{02} & t_{03} \\
t_{10} & t_{11} & t_{12} & t_{13} \\
t_{20} & t_{21} & t_{22} & t_{23} \\
0.0 & 0.0 & 0.0 & 1.0
\end{bmatrix}
```

the pose/0.txt file would then be:

> 0.173196 0.872300 0.457271 -4.817948
> -0.948179 0.022103 0.316968 0.655692
> 0.266383 -0.488472 0.830924 -24.168480
> 0.000000 0.000000 0.000000 1.000000

Quoting the [polyform](https://github.com/PolyCam/polyform/tree/main) page:

> The coordinate system of the camera poses follows the ARKit gravity aligned convention which you can read about [here](https://developer.apple.com/documentation/arkit/arconfiguration/worldalignment/gravity). In short, this is a right-handed coordinate system where the `+Y axis` points up, and `-Z axis` points in the direction that the camera was pointing when the session started, and perpendicular to gravity. Note: depending on the coordinate system convention of your downstream application you might have to apply an additional rotation to the camera transform to get the conventions to match.
>

I do then apply a 90 degrees X rotation matrix in order to have the Z axis up.

```math
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
\cdot
\begin{bmatrix}
t_{00} & t_{01} & t_{02} & t_{03} \\
t_{10} & t_{11} & t_{12} & t_{13} \\
t_{20} & t_{21} & t_{22} & t_{23} \\
0.0 & 0.0 & 0.0 & 1.0
\end{bmatrix}
```
Resulting in
pose/0.txt

> 0.173196 0.872300 0.457271 -4.817948
> -0.266383 0.488472 -0.830924 24.168480
> -0.948179 0.022103 0.316968 0.655692
> 0.000000 0.000000 0.000000 1.000000

I then get the intrinsic from the first frame:
```math
\begin{bmatrix}
fx & 0.0 & cx & 0.0 \\
0.0 & fy & cy & 0.0 \\
0.0 & 0.0 & 1.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 1.0
\end{bmatrix}
```

> 849.073700 0.000000 507.032900 0.000000
> 0.000000 849.073700 383.280800 0.000000
> 0.000000 0.000000 1.000000 0.000000
> 0.000000 0.000000 0.000000 1.000000

PolyCam images resolution differs from the depth images, since the iOS Lidar is limited to 192x256px
Image: 1024x768
Depth: 256x192

I then resize them to 640x480 to fit your test dataset. By downsampling the color images and upsampling the depth images.

Since the iPad scans are taken in a vertical orientation, but saved horizontally, I also implemented a script that applies a rotation to the images, as well as to the camera poses and intrinsic. eg. from (480x640) to (480x640)

Now to my problem:

I'm getting a good segmentation from the mask3d part, but when checking the crops I'm only getting crops from few images (like max 4-5 from the 100-200 loaded), this way I'm not getting crops from objects that would be present from other images shot from other angles. crops also seems redundant within the only few objects selected. Sec. 3.2.1 of the paper.

Even within the objects where I could see some decent cropping was done, they don't get masked when queried in the visualization tool.

I've tried several scenes, from simple to complex, with and without image rotation, and with different parameters, with no success.

**Comment by parodiniccolo** [comment]
@aycatakmaz @elisabettafedele

**Comment by aycatakmaz** [comment]
Hi Niccolò,

Sorry for our late reply!

I took a look at the information you shared here. If I understand correctly, you resize both the depth images and the RGB images to 640, 480, which is great.

There are two potential issues that come to my mind, and it could arise due to the settings in the https://github.com/OpenMask3D/openmask3d/blob/main/run_openmask3d_single_scene.sh file:
1- It could be that SCENE_INTRINSIC_RESOLUTION is not set correctly. This should be the original resolution of the images that was used in the intrinsic matrix, SCENE_INTRINSIC_RESOLUTION="[height,width]". If I understand correctly, these values refer to 768 and 1024 in your case. So the resolution according to the intrinsic matrix should be set as an input in the config file.

2- The DEPTH_SCALE parameter should also be set correctly. Our depth images (from the ScanNet dataset) are scaled by 1000, so in order to convert them to meters, we divide the depth values we load by 1000 (which is the DEPTH_SCALE). If your depth values are already in meters, you should set this number to 1.

I hope this helps, and once again sorry for the late reply.

Best,
Ayca

**Comment by aycatakmaz** [comment]
I am closing the issue, feel free to re-open it if the issue continues!
