### ISSUE TITLE
Visualization tool for the outputs

### ISSUE THREAD

**Issue by lluisb3** [OpenMask3D/openmask3d#4]
Thanks @aycatakmaz, @elisabettafedele and @francisengelmann to make available this incredible and very promising tool! I run your alghorithm in a scene recorded by myself with the following outputs:
-crops
-hydra_outputs
-<scene>_masks.pt
<scene>_openmask3d_features.npy

Now I was wondering if the tool you use to visualize the ouputs toghter with the .ply file is available or if you could provide some hints on how to achive it! Thanks.

Also I was wondering if the .ply file that you use to analyze a new scene is a point cloud (with only points) or a mesh (with vertices and triangles)? Or does not matter and actually the alghorithm performs well with both?

And I detected and small problem. I had my color images saved in .png and when running the code even specifying in run_openmask3d_single_scene.sh file, IMG_EXTENSION=".png" the alghrithm was crassing throwing the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/ither1/openmask3d/resources/data_meeting/color/0.jpg'

I saved the color images in .jpg and everything worked fine for me.

Thanks again for the contribution!

**Comment by elisabettafedele** [comment]
Dear Luis,

Thanks for your interest in our work!

Regarding the visualisations, we are planning to update the repository with a visualisation script in the coming days, so that it will be easy to visualise the results.

Regarding the extension of the images, thank you for pointing this out. There was a small bug that should be fixed now.

Let us know if you have any further question!

Best,
Elisabetta

**Comment by lluisb3** [comment]
Thanks a lot for the update! That's really good news, it will be very useful for me to visualize the results as you do in your paper. 

Thanks again for this contribution!

Best,
Lluis

**Comment by aycatakmaz** [comment]
Hi Luis,

We have pushed a commit that adds a simple visualization script [viz_sim_score_export.py](https://github.com/OpenMask3D/openmask3d/blob/main/openmask3d/visualization/viz_sim_score_export.py). In order to visualize similarity scores between the OpenMask3D features and the query embedding as a heatmap, one just needs to set the following variables:

path_scene_pcd: Path to the scene point cloud/mesh (*.ply)
path_pred_masks: Path to the predicted instance masks (*.pt)
path_openmask3d_features: Path to the per-mask OpenMask3D features (*.npy)
query_text: Intended query text as a string, e.g. "watch a movie"
The script will automatically visualize the similarity scores as a heatmap, and show the results in an Open3D visualization window. Alternatively, you can also export a .ply file with the point cloud colored with the similarity heatmap colors per point.

#7

**Comment by lluisb3** [comment]
Hi @aycatakmaz, 

Thanks a lot for the update! I will try to run the script on my own data as soon as possible!
