### ISSUE TITLE
Could you please provide code for  visualization the open vocabulary segmentation result?

### ISSUE THREAD

**Issue by LilRedWu** [OpenMask3D/openmask3d#7]

**Comment by aycatakmaz** [comment]
Hi, 

Thank you for your interest in our work. We have pushed a commit that adds a simple visualization script  [viz_sim_score_export.py](https://github.com/OpenMask3D/openmask3d/blob/main/openmask3d/visualization/viz_sim_score_export.py). In order to visualize similarity scores between the OpenMask3D features and the query embedding as a heatmap, one just needs to set the following variables:

- `path_scene_pcd`: Path to the scene point cloud/mesh (*.ply)
- `path_pred_masks`: Path to the predicted instance masks (*.pt)
- `path_openmask3d_features`: Path to the per-mask OpenMask3D features (*.npy)
- `query_text`: Intended query text as a string, e.g. "watch a movie"

The script will automatically visualize the similarity scores as a heatmap, and show the results in an Open3D visualization window. Alternatively, you can also export a `.ply` file with the point cloud colored with the similarity heatmap colors per point.
